---

# Unix users to create. All users defined here are root users (access
# to docker as well as wheel).
users:
  - mxs
  - faltad
  - ironzorg
  - notoriouspig

email_contact: "mxs@sbrk.org"

# Domains & services to manage.
#
# Config:
#
# - domain: domain for which to generate an SSL certificate,
# - type: template configuration used the generate the config.
#
# Other entries are directly passed to the template configuration.
websites:

  - domain: necromancer.sbrk.org
    template_config: static.skeleton
    data: /srv/http/necromancer.sbrk.org/public

  - domain: blz.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10001

  - domain: sandwalker.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10002

  - domain: mxs.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10003
    landing_port: 10004
    landing_static: highlander

  - domain: landing.mxs.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10004

  - domain: detours.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10005

  - domain: data.mxs.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10006

  - domain: aimxhaisse.com
    template_config: proxy_local_port.skeleton
    local_port: 10003
    landing_port: 10004
    landing_static: highlander

  - domain: sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10007

  - domain: an-aer.bzh
    template_config: proxy_local_port.skeleton
    local_port: 10008

  - domain: ftp.dkwe.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10009

  - domain: matrix.sbrk.org
    template_config: matrix_nginx.skeleton
    # NOTE: port 11002 is taken by Matrix federation traffic
    local_port: 11001

  - domain: matrix-web.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 11003
    secure_headers: true

  - domain: git.sbrk.org
    template_config: proxy_local_port.skeleton
    # NOTE: port 11005 is taken by the Gitea SSH server
    local_port: 11004
    secure_headers: true

# Unlike websites that are served by the HTTP server and whose configuration is
# automatically modified, the services below are standalone
services:

  - domain: voip.sbrk.org
